import express from 'express';
import { query } from '../db.js';
import { authMiddleware, requireAdmin } from '../middleware/auth.js';
const router = express.Router();
const id = x => Number.isSafeInteger(Number(x)) && Number(x) > 0 ? Number(x) : null;
router.get('/', async (req,res,next) => { try { const { rows } = await query('SELECT b.*, u.username AS "authorUsername" FROM blogs b LEFT JOIN users u ON u.id = b.author_id ORDER BY b."createdAt" DESC'); res.json(rows); } catch(e){next(e);} });
router.get('/:id', async (req,res,next) => { try { const blogId=id(req.params.id); if(!blogId)return res.status(400).json({error:'Invalid blog id'}); const {rows}=await query('UPDATE blogs SET views = views + 1, "updatedAt" = NOW() WHERE id=$1 RETURNING *',[blogId]); if(!rows[0])return res.status(404).json({error:'Blog not found'});res.json(rows[0]);}catch(e){next(e);} });
router.post('/',authMiddleware,requireAdmin,async(req,res,next)=>{try{const {title,content}=req.body;if(!title?.trim()||!content?.trim())return res.status(400).json({error:'title and content are required'});const {rows}=await query('INSERT INTO blogs (title,content,author,author_id,tags,"updatedAt") VALUES ($1,$2,$3,$4,$5::jsonb,NOW()) RETURNING *',[title.trim(),content.trim(),req.body.author?.trim()||'Administrator',req.userId,JSON.stringify(Array.isArray(req.body.tags)?req.body.tags:[])]);res.status(201).json(rows[0]);}catch(e){next(e);}});
router.delete('/:id',authMiddleware,requireAdmin,async(req,res,next)=>{try{const blogId=id(req.params.id);if(!blogId)return res.status(400).json({error:'Invalid blog id'});const r=await query('DELETE FROM blogs WHERE id=$1',[blogId]);if(!r.rowCount)return res.status(404).json({error:'Blog not found'});res.status(204).send();}catch(e){next(e);}});
export default router;
